[package]
name = "devsparkle/maid"
description = "A hassle-free Roblox library to manage object cleanup!"
version = "2.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]