[package]
name = "devsparkle/maid"
description = "A hassle-free Roblox library to manage object cleanup!"
version = "2.1.0"
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
