name: "Roblox"

on:
  push:
    paths:
      - "wally.toml"

jobs:
  workflow:
    uses: ungms/.github/.github/workflows/roblox.yml@main
    
    secrets: inherit
    permissions:
        contents: write
